excluded_words:
  - SequencErr
  - sequencerr
  - rnaseq
  - Gencode
  - project-rnaseq
  - rnaseq-expression-classification
  - Unstranded
  - DNAnexus
  - rnaseq-expression-workflow-options-new-ui
  - rnaseq-expression-workflow-realignment-options-new-ui

  # Names
  - Dongren
  - Kolekar
  - Nakitandwe
  - Pandurang
  - Ren
  - Robison
  - Shao
  - Szlachta
  - Xiaotu
  - Yanling
  - Ying
  - Zhaoming
