dictionaries:
  - en
  - en_GB

excluded_words:
  - rnaseq
  - Gencode
  - project-rnaseq
  - rnaseq-expression-classification
  - Unstranded
  - DNAnexus
  - rnaseq-expression-workflow-options-new-ui
  - rnaseq-expression-workflow-realignment-options-new-ui
  - stjude
  - NeoepitopePred
  - neoepitope
  - ipynb
  - bamqc
  - qualimap
  - GDC's
  - gdc-mrnaseq-pipeline
  - gdc-reference-genome
  - ENCODE's
  - encode-rnaseq-pipeline
  - gtex-rnaseq-pipeline
  - sjdbOverhang
  - exome
  - omics
  - omics-based
  - fastqc
  - ngsderive
  - SamToFastq
  - fastq
  - fastq-screen
  - unstranded
  - conda
  - bioconda
  - conda-forge
  - multiqc
  - fastqs
  - fqlib
  - readlen
  - gtf
  - Indel
  - aln
  - bwa
  - sampe
  - LiftoverVcf
  - vep
  - bgzipped
  - tabixed
  - gatk-validator
  - fathmm
  - in-silico
  - lrt
  - bcftools
  - isoforms
  - GATK
  - GATK's

  # Names
  - Dongren
  - Kolekar
  - Nakitandwe
  - Pandurang
  - Ren
  - Robison
  - Shao
  - Szlachta
  - Xiaotu
  - Yanling
  - Ying
  - Zhaoming
