site_name: 'St. Jude Cloud Documentation'
# site_url: 'https://www.stjude.cloud/docs/'
theme:
  name: 'material'
  custom_dir: 'mkdocs-stjudecloud/material'
  logo: 'images/stjude-logo-child-white.png'
  font: false
  favicon: 'images/favicon.ico'

extra_css:
  - css/extra.css

nav:
  - Welcome to St. Jude Cloud: index.md 
  - COVID-19 Response:
      - Introduction: guides/covid-19/index.md
      - Getting started: guides/covid-19/getting-started.md
      - Data upload (local): guides/covid-19/upload-local.md
      - Data upload (HPC): guides/covid-19/upload-cluster.md
      - Creating a cloud app: guides/covid-19/creating-a-cloud-app-covid.md
      - Interactive nodes: guides/covid-19/interactive-node.md
  - Account and Billing: ./account-and-billing.md
  - Data Guides: 
      - About Our Data: guides/data/about-our-data.md
      - Making a Data Request: guides/data/data-request.md
      - Working with Our Data: guides/data/working-with-our-data.md
      - Creating a Cloud App: guides/data/creating-a-cloud-app.md
      - Data Transfer Application: guides/data/data-transfer-app.md
      - Command Line Interaction: guides/data/command-line.md
  - Tool Guides:
      - Pecan PIE: guides/tools/pecan-pie.md
      - NeoepitopePred: guides/tools/neoepitope.md
      - ChIP-Seq Peak Calling: guides/tools/chipseq.md
      - Rapid RNA-Seq Fusion Detection: guides/tools/rapid-rnaseq.md
      - WARDEN Differential Expression Analysis: guides/tools/warden.md
      - Mutational Signatures: guides/tools/mutational-signatures.md
      - Cis-X: guides/tools/cis-x.md
  - Visualization Guides:
      - PeCan Data Portal : guides/portals/pecan.md
      - Genome Paint : guides/portals/genome-paint.md
      - Sickle Cell Genomics Portal : guides/portals/sickle-cell.md
  - Forms:
      - Filling out a Data Access Agreement: guides/forms/how-to-fill-out-DAA.md 
      - Filling out an Extension Addendum: guides/forms/how-to-fill-out-Extension.md
  - Citing St. Jude Cloud: citing-stjude-cloud.md
  - Frequently Asked Questions: faq.md
  - Glossary: glossary.md

# Repository
repo_name: 'stjudecloud/docs'
repo_url: 'https://github.com/stjudecloud/docs'
edit_uri: 'edit/master/docs'

# Copyright
copyright: "Copyright &copy; 2017 - 2019 St. Jude Children's Research Hospital"

# Extensions
markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - pymdownx.inlinehilite
    - pymdownx.tasklist


# Extra
# NOTE: The CI server depends on this entry being last, as it writes the commit
# hash variable to this file by appending it.
extra:
  social:
    - type: 'facebook'
      link: 'https://www.facebook.com/stjuderesearch/'
    - type: 'twitter'
      link: 'https://twitter.com/stjuderesearch?lang=en'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/st-jude-childrens-research-hospital'
    - type: 'github'
      link: 'https://github.com/stjude'
