site_name: "St. Jude Cloud Documentation"
# site_url: 'https://www.stjude.cloud/docs/'
theme:
  name: "material"
  custom_dir: "mkdocs-stjudecloud/material"
  logo: "images/stjude-logo-child-white.png"
  font: false
  favicon: "images/favicon.ico"
  feature:
    tabs: true

extra_css:
  - css/extra.css

nav:
  - Overview: index.md
  - About our Ecosystem: ecosystem.md
  - Genomics Platform:
      - Getting Started: guides/genomics-platform/index.md
      - Accounts and Billing: guides/genomics-platform/accounts-and-billing.md
      - Requesting Data:
          - About our Data: guides/genomics-platform/requesting-data/about-our-data.md
          - Making a Data Request: guides/genomics-platform/requesting-data/data-request.md
          - Filling Out a Data Access Agreement: guides/genomics-platform/requesting-data/how-to-fill-out-DAA.md
          - About our Decision Process & Terminology: guides/genomics-platform/requesting-data/glossary.md
      - Managing Data:
          - Managing Data Overview: guides/genomics-platform/managing-data/working-with-our-data.md
          - Upload/Download Data (local): guides/genomics-platform/managing-data/upload-local.md
          - Upload Data (HPC): guides/genomics-platform/managing-data/upload-cluster.md
          - Renewing your Data Access: guides/genomics-platform/managing-data/how-to-fill-out-Extension.md
      - Analyzing Data:
          - Command Line Interaction: guides/genomics-platform/analyzing-data/command-line.md
          - Running our Workflows: guides/genomics-platform/analyzing-data/running-sj-workflows.md
          - Workflow Guides:
              - ChIP-Seq Peak Calling: guides/genomics-platform/analyzing-data/chipseq.md
              - cis-X: guides/genomics-platform/analyzing-data/cis-x.md
              - MethylationToActivity: guides/genomics-platform/analyzing-data/methylation-to-activity.md
              - Mutational Signatures: guides/genomics-platform/analyzing-data/mutational-signatures.md
              - Rapid RNA-Seq Fusion Detection: guides/genomics-platform/analyzing-data/rapid-rnaseq.md
              - RNA-Seq Expression Classification: guides/genomics-platform/analyzing-data/rnaseq-expression-classification.md
              - SequencErr: guides/genomics-platform/analyzing-data/sequencerr.md
              - WARDEN Differential Expression Analysis: guides/genomics-platform/analyzing-data/warden.md
              # XenoCP: guides/genomics-platform/analyzing-data/xeno-cp.md
              # RNA Indel: guides/genomics-platform/analyzing-data/rna-indel.md
              # FKPM: guides/genomics-platform/analyzing-data/fkpm.md
          - Creating your own Workflow: guides/genomics-platform/analyzing-data/creating-a-cloud-app.md
          - Interactive nodes: guides/genomics-platform/analyzing-data/interactive-node.md
      - Frequently Asked Questions: guides/genomics-platform/faq.md
  - PeCan:
      - Getting Started: guides/pecan/index.md
      - Pecan PIE: guides/pecan/pecan-pie.md
  - Visualization Community:
      - Getting Started: guides/visualization-community/index.md
      - ProteinPaint: guides/visualization-community/proteinpaint.md
      - GenomePaint: guides/visualization-community/genomepaint.md
      - Frequently Asked Questions: guides/visualization-community/faq.md
      #- SJ Charts: guides/visualization-community/sjcharts.md
      #- t-SNE Charts: guides/visualization-community/t-sne-charts.md
  - Portals:
    - Childhood Solid Tumor Network Portal: guides/cstn.md
    - Pediatric Brain Tumor Portal: guides/pbtp.md
  - ProteinPaint:
    - ProteinPaint: 
        - Introduction: guides/proteinpaint/index.md
        - User Guide:
            - Getting Started: guides/proteinpaint/navigating-the-protein-diagram.md
            - Loading Datasets: guides/proteinpaint/loading-datasets.md
            - Viewing SNV/Indel Mutations: guides/proteinpaint/view-mutation-details.md
            - Viewing Gene Fusions: guides/proteinpaint/exploring-gene-fusions.md
            - Viewing Expression Data: guides/proteinpaint/exploring-gene-expression.md
            - Filtering Mutations: guides/proteinpaint/filtering-mutations.md
            - Exporting Figures and Data: guides/proteinpaint/exporting-figures-and-data.md
            - Using the Gene Table: guides/proteinpaint/advanced-guides/using-the-gene-table.md
            - Using the Sample Table: guides/proteinpaint/advanced-guides/using-the-sample-table.md
            - Using the Heatmap: guides/proteinpaint/advanced-guides/using-the-heatmap.md
            - Using Disease Pie Charts: guides/proteinpaint/advanced-guides/using-disease-pie-charts.md
            - Stratifying Mutations by Cancer Subtype: guides/proteinpaint/advanced-guides/stratify-mutation-by-cancer-subtype.md
        - File Formats:
            - SNV and Indel: guides/proteinpaint/file-formats/snv-and-indel.md
            - SV and fusion transcript: guides/proteinpaint/file-formats/sv-and-fusion.md
            - Copy Number Variants: guides/proteinpaint/file-formats/cnv.md
            - Internal tandem duplications: guides/proteinpaint/file-formats/itd.md
            - Intragenic deletion: guides/proteinpaint/file-formats/intragenic-deletion.md
            - Trunction, N-loss or C-loss: guides/proteinpaint/file-formats/truncation.md
            - JSON-BED: guides/proteinpaint/file-formats/json-bed.md
            - Splice Junction: guides/proteinpaint/file-formats/splice-junction.md
            - Profile-Gene-Value: guides/proteinpaint/file-formats/pgv.md
            - Bampile: guides/proteinpaint/file-formats/bampile.md
        - Advanced Usage:
            - Add Custom Protein Domains: guides/proteinpaint/advanced-guides/custom-protein-domains.md
            - Using Custom Tracks: guides/proteinpaint/advanced-guides/using-custom-tracks.md
            - Visualize Your Mutation Data: guides/proteinpaint/advanced-guides/visualize-custom-mutations.md
            - Loading SNV/Indel Mutations from a File: guides/proteinpaint/advanced-guides/loading-snv-indel-mutations-from-a-file.md
            - Uploaded Mutation Data User Interface: guides/proteinpaint/advanced-guides/uploaded-mutation-data-user-interface.md
            - Loading a TCGA MAF File: guides/proteinpaint/advanced-guides/loading-tcga-maf-file.md
            - Loading a VCF File: guides/proteinpaint/advanced-guides/using-a-vcf-file.md
        - Developer's Guide:
            - Embedding ProteinPaint: guides/proteinpaint/developers-guide/embedding-proteinpaint.md
            - URL Parameters: guides/proteinpaint/developers-guide/url-parameters.md
            - Organizing Data into a Study View: guides/proteinpaint/developers-guide/organizing-data-into-a-study-view.md
    - GenomePaint:
        - User Guide: guides/genomepaint/index.md
  - Studies:
      - About: guides/studies/index.md
      - Sickle Cell: guides/studies/sickle-cell.md
  - Frequently Asked Questions: faq.md
  - Citing St. Jude Cloud: citing-stjude-cloud.md

# Repository
repo_name: "stjudecloud/docs"
repo_url: "https://github.com/stjudecloud/docs"
edit_uri: "edit/master/docs"

# Copyright
copyright: "Copyright &copy; 2020 St. Jude Children's Research Hospital"

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      toc_depth: "2-5"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra
# NOTE: The CI server depends on this entry being last, as it writes the commit
# hash variable to this file by appending it.
extra:
  social:
    - type: "facebook"
      link: "https://www.facebook.com/stjuderesearch/"
    - type: "twitter"
      link: "https://twitter.com/stjuderesearch?lang=en"
    - type: "linkedin"
      link: "https://www.linkedin.com/company/st-jude-childrens-research-hospital"
    - type: "github"
      link: "https://github.com/stjude"
