site_name: 'St. Jude Cloud Documentation'
site_url: 'https://www.stjude.cloud/docs/'
theme:
  name: 'material'
  custom_dir: 'mkdocs-material/material'
  logo: 'images/stjude-logo-child-white.png'
  font: false
  favicon: 'assets/images/favicon.ico'

extra_css:
  - css/extra.css

pages:
  - 'Welcome to St. Jude Cloud': 'index.md'
  - 'Genomics Platform': 
      - 'Requesting Data':
          - 'About our Data': 'guides/genomics-platform/requesting-data/about-our-data.md'
          - 'Creating an Account': 'guides/genomics-platform/requesting-data/create-an-account.md'
          - 'Making a Data Request': 'guides/genomics-platform/requesting-data/data-request.md'
          - 'Filling Out a Data Access Agreement': 'guides/genomics-platform/requesting-data/how-to-fill-out-DAA.md' 
          - 'About our Decision Process & Terminology': 'guides/genomics-platform/requesting-data/glossary.md'
      - 'Managing Data':
          - 'Managing Data Overview': 'guides/genomics-platform/managing-data/working-with-our-data.md'
          - 'Uploading/Downloading Data': 'guides/genomics-platform/managing-data/data-transfer-app.md'
          - 'Renewing your Data Access': 'guides/genomics-platform/managing-data/how-to-fill-out-Extension.md'
      - 'Analyzing Data':
          - 'SJ Cloud Workflows':
              - 'NeoepitopePred': 'guides/genomics-platform/analyzing-data/neoepitope.md'
              - 'ChIP-Seq Peak Calling': 'guides/genomics-platform/analyzing-data/chipseq.md'
              - 'Rapid RNA-Seq Fusion Detection': 'guides/genomics-platform/analyzing-data/rapid-rnaseq.md'
              - 'WARDEN Differential Expression Analysis': 'guides/genomics-platform/analyzing-data/warden.md'
              - 'Mutational Signatures': 'guides/genomics-platform/analyzing-data/mutational-signatures.md'
              - 'Cis-X': 'guides/genomics-platform/analyzing-data/cis-x.md'
              - 'M2A': 'guides/genomics-platform/analyzing-data/m2a.md'
              - 'XenoCP': 'guides/genomics-platform/analyzing-data/xeno-cp.md'
              - 'RNA Indel': 'guides/genomics-platform/analyzing-data/rna-indel.md'
              - 'FKPM': 'guides/genomics-platform/analyzing-data/fkpm.md'
          - 'Command Line Interaction': 'guides/genomics-platform/analyzing-data/command-line.md'
          - 'Creating your own Workflow': 'guides/genomics-platform/analyzing-data/creating-a-cloud-app.md'
  - 'PeCan':
      - 'PeCan homepage': 'guides/applications/PeCan/pecan.md'
      - 'Pecan PIE': 'guides/applications/PeCan/pecan-pie.md'
  - 'Model Systems':
      - 'CSTN': 'guides/applications/model-systems/cstn.md'
      - 'PBTP': 'guides/applications/model-systems/pbtp.md'
  - 'Visualization Community':
      - 'About': 'guides/visualization-community/viz-com-about.md'
      - 'ProteinPaint' : 'guides/visualization-community/protein-paint.md'
      - 'Genome Paint' : 'guides/visualization-community/genome-paint.md'
      - 'SJ Charts': 'guides/visualization-community/sj-charts.md'
      - 't-SNE Charts': 'guides/visualization-community/t-sne-charts.md'
  - 'Studies':
      - 'About/Common Features': 'guides/studies-about.md'
      - '' : 'guides/portals/sickle-cell.md'
  - 'Frequently Asked Questions': 'faq.md'
  - 'Citing St. Jude Cloud': 'citing-stjude-cloud.md'

# Repository
repo_name: 'stjudecloud/docs'
repo_url: 'https://github.com/stjudecloud/docs'
edit_uri: 'edit/master/docs'

# Copyright
copyright: "Copyright &copy; 2017 - 2019 St. Jude Children's Research Hospital"


# Extensions
markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - pymdownx.inlinehilite


# Extra
# NOTE: The CI server depends on this entry being last, as it writes the commit
# hash variable to this file by appending it.
extra:
  social:
    - type: 'facebook'
      link: 'https://www.facebook.com/stjuderesearch/'
    - type: 'twitter'
      link: 'https://twitter.com/stjuderesearch?lang=en'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/st-jude-childrens-research-hospital'
    - type: 'github'
      link: 'https://github.com/stjude'
