site_name: "St. Jude Cloud Documentation"
# site_url: 'https://www.stjude.cloud/docs/'
theme:
  name: "material"
  custom_dir: "mkdocs-stjudecloud/material"
  logo: "images/stjude-logo-child-white.png"
  font: false
  favicon: "images/favicon.ico"
  feature:
    tabs: true

extra_css:
  - css/extra.css

nav:
  - Overview: index.md
  - About our Ecosystem: ecosystem.md
  - COVID-19 Quickstart:
      - Introduction: guides/covid-19/index.md
      - Getting started: guides/covid-19/getting-started.md
      - Data upload (local): guides/covid-19/upload-local.md
      - Data upload (HPC): guides/covid-19/upload-cluster.md
      - Creating a cloud app: guides/covid-19/creating-a-cloud-app-covid.md
      - Interactive nodes: guides/covid-19/interactive-node.md
      - Visualizing NGS data: guides/covid-19/visualizing-ngs-data.md
  - Genomics Platform:
      - Getting Started: guides/genomics-platform/index.md
      - Accounts and Billing: guides/genomics-platform/accounts-and-billing.md
      - Requesting Data:
          - About our Data: guides/genomics-platform/requesting-data/about-our-data.md
          - Making a Data Request: guides/genomics-platform/requesting-data/data-request.md
          - Filling Out a Data Access Agreement: guides/genomics-platform/requesting-data/how-to-fill-out-DAA.md
          - About our Decision Process & Terminology: guides/genomics-platform/requesting-data/glossary.md
      - Managing Data:
          - Managing Data Overview: guides/genomics-platform/managing-data/working-with-our-data.md
          - Uploading/Downloading Data: guides/genomics-platform/managing-data/data-transfer-app.md
          - Renewing your Data Access: guides/genomics-platform/managing-data/how-to-fill-out-Extension.md
      - Analyzing Data:
          - Command Line Interaction: guides/genomics-platform/analyzing-data/command-line.md
          - Running our Workflows: guides/genomics-platform/analyzing-data/running-sj-workflows.md
          - SJ Cloud Workflows:
              - NeoepitopePred: guides/genomics-platform/analyzing-data/neoepitope.md
              - ChIP-Seq Peak Calling: guides/genomics-platform/analyzing-data/chipseq.md
              - Rapid RNA-Seq Fusion Detection: guides/genomics-platform/analyzing-data/rapid-rnaseq.md
              - WARDEN Differential Expression Analysis: guides/genomics-platform/analyzing-data/warden.md
              - Mutational Signatures: guides/genomics-platform/analyzing-data/mutational-signatures.md
              # Cis-X: guides/genomics-platform/analyzing-data/cis-x.md
              # M2A: guides/genomics-platform/analyzing-data/m2a.md
              # XenoCP: guides/genomics-platform/analyzing-data/xeno-cp.md
              # RNA Indel: guides/genomics-platform/analyzing-data/rna-indel.md
              # FKPM: guides/genomics-platform/analyzing-data/fkpm.md
          - Creating your own Workflow: guides/genomics-platform/analyzing-data/creating-a-cloud-app.md
  - PeCan:
      - Getting Started: guides/pecan/index.md
      - Pecan PIE: guides/pecan/pecan-pie.md
  #- Model Systems:
  #- CSTN: guides/model-systems/cstn.md
  #- PBTP: guides/model-systems/pbtp.md
  - Visualization Community:
      - Getting Started: guides/visualization-community/index.md
      - ProteinPaint: guides/visualization-community/proteinpaint.md
      - Genome Paint: guides/visualization-community/genomepaint.md
      #- SJ Charts: guides/visualization-community/sjcharts.md
      #- t-SNE Charts: guides/visualization-community/t-sne-charts.md
  - Studies:
      - About: guides/studies/index.md
      - Sickle Cell: guides/studies/sickle-cell.md
  - Frequently Asked Questions: faq.md
  - Citing St. Jude Cloud: citing-stjude-cloud.md

# Repository
repo_name: "stjudecloud/docs"
repo_url: "https://github.com/stjudecloud/docs"
edit_uri: "edit/master/docs"

# Copyright
copyright: "Copyright &copy; 2020 St. Jude Children's Research Hospital"

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra
# NOTE: The CI server depends on this entry being last, as it writes the commit
# hash variable to this file by appending it.
extra:
  social:
    - type: "facebook"
      link: "https://www.facebook.com/stjuderesearch/"
    - type: "twitter"
      link: "https://twitter.com/stjuderesearch?lang=en"
    - type: "linkedin"
      link: "https://www.linkedin.com/company/st-jude-childrens-research-hospital"
    - type: "github"
      link: "https://github.com/stjude"
