name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: docs
          channels: conda-forge,bioconda,defaults
      - name: Compile
        shell: bash -l {0}
        run: bash bin/ci-build.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./site
          user_name: "St. Jude Cloud"
          user_email: support@stjude.cloud
          commit_message: "Deployed from '${{ github.event.head_commit.message }}'"
